


get_sytse_pdp11:
	wget https://pdp2011.sytse.net/wordpress/wp-content/uploads/2021/05/pdp11-20210530.tar.gz
	tar -xf pdp11-20210530.tar.gz

all: get_sytse_pdp11

clean:
	rm -rf pdp11-20210530
	rm pdp11-20210530.tar.gz